version: '3.7'

services:
  radcam-spy:
    build: .
    container_name: blueos-radcam-spy
    network_mode: host
    ports:
      - "9850:9850"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
